### ISSUE TITLE
Integrate list of communities into form

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-intake#116]

**Comment by rgreensp** [comment]
When filling out a "Last mile project" the form asks "which named communities this will reach".
The data team has provided a list of communities by zone.
For each zone form, include list of checkboxes for communities so that respondents can select communities in that zone they will reach.

**Comment by elliottSlee** [comment]
@BryanGK can we remember to estimate this?

**Comment by BryanGK** [comment]
@elliottSlee yep no worries. Let's get some input on best ways to handle this.

@wenzowski What are some strategies we can employ to get this done?
