### ISSUE TITLE
Optimize Resource Values

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#149]
We should optimize resource values on the openshift cluster, we have resources available and we ought to make use of them.

**Comment by elliottSlee** [comment]
Resource values - ie., sysdig, memory usage

- Long running quota is 4gB using 3.840 (93.8% memory limit)

Docker images. Can do, but lower priority.

Still listed as nice to have. Prioritize if requested.

**Comment by rgreensp** [comment]
Less disruption in prod for RTP is preferable. Closing this issue.
