### ISSUE TITLE
Tying saved data to user ID not the session ID. Draft status/state. Ability to see draft data.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#153]
As a user
I want to start on one device then continue on another
So that I can complete my request on my favorite device

As a user
I want to have my data saved between browser sessions
so that I don't have to re-enter any information

Given I am logged in
when I type in the form and I click the continue button
then the stuff I typed in the form is saved in the applications table and the status is set as draft

- [x] create button creates row for application
- [x] row for application has "status" column, draft by default
- [ ] root for the form will be /[applicationId]/[page] (not currently our startegy)
- [x] useSession set to false, implement onPost function to use graphQL updateApplication mutation

**Comment by BryanGK** [comment]
https://github.com/button-inc/service-development-toolkit/tree/develop/packages/form-schema#custom-data-handling

**Comment by BryanGK** [comment]
Issue closed by merging #199 - CLOSED
