### ISSUE TITLE
Returning user sees last saved page on dashboard

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#156]
### User Story
As a returning user, after I login, I want to know what page I was last on on so that I can orient myself.

### Acceptance Criteria
Given that a returning user logs back in with a BCeID that has been used before, when they click login, then they will be directed to the landing page which will have a section that says the last page they pressed "Continue" on.

**Comment by RajGurtata** [comment]
Per Rachel- Not implement as part of RTP
