### ISSUE TITLE
Help in navbar

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#159]
### User Story
As a user, I want to be able to find help while completing the form where I usually expect it in the navbar to that I can contact a human if I need help.

### Acceptance Criteria
Given that a user is on any page of the form, when they click on the word [Help](mailto:connectingcommunitiesbc@gov.bc.ca) in the navbar, then they are directed to email connectingcommunitiesbc@gov.bc.ca.

**Comment by rgreensp** [comment]
Program name won't be announced. Won't have email yet.

**Comment by elliottSlee** [comment]
Program name is now announced and Susan wrote instructions for each page that could be replaced by a Help button.
