### ISSUE TITLE
Optional description

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#164]
As a user, I want to know which fields are optional so that I can skip them if need be.

**Comment by elliottSlee** [comment]
When there are more required than optional, it's more clear to users and we're more likely to get completed data when optional fields are marked "optional" instead of required marked with an asterisk. https://developer.gov.bc.ca/Design-System/Forms
"optional...is preferable in long forms with multiple required fields" https://xd.adobe.com/ideas/principles/web-design/best-practices-form-design/

**Comment by rgreensp** [comment]
Already in wireframes.
