### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#182]
### User Story
As a user, I want to see Home, Disclaimer, Privacy, Accessibility, and Copyright in the footer so that I can access pertinent information when I am concerned about legality, privacy, accessibility, and reproducibility issues with the webpage.

### Acceptance Criteria
It's hard to write good acceptance criteria for this without just giving instructions. So here are the instructions and links from the BC Design System: https://developer.gov.bc.ca/Design-System/Footer-Basic

**Comment by elliottSlee** [comment]
Removed "Given that a user is on any page of the form, when they click on home in the footer, then they will be directed to the program information page that Catherine created (need URL)." from the acceptance criteria because the form may launch before the program launches so that website won't be available.

**Comment by BryanGK** [comment]
Footer complete - CLOSED
