### ISSUE TITLE
Page 1 Organization Profile

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/connectivity-intake#184]

**Comment by zoeyli-46** [comment]
All fields are required unless marked optional

**Comment by zoeyli-46** [comment]
No need for a cancel button. Responses are auto-saved, so a cancel button provides no functionality in the traditional sense of cancelling an entry. Including a logout link above serves the intended effect.

**Comment by BryanGK** [comment]
Done - CLOSED
