### ISSUE TITLE
2 - Card Title Typo

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/connectivity-intake#212]

**Comment by zoeyli-46** [comment]
The landing page says "Connected communities BC", it should say "Request to Participate" https://bcgov.sharepoint.com/:i:/r/teams/04708/Shared%20Documents/Research/Usability%20Testing/Screenshots/2%20-%20log%20out%20button,%20landing%20page%20card%20title.png?csf=1&web=1&e=Mc9J11

**Comment by BryanGK** [comment]
This has been fixed - CLOSED
