### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/connectivity-intake#218]

**Comment by zoeyli-46** [comment]
Could there be a line break between the question and the form field title? The screenshot has red markings to show as an example where there should be a line break
https://bcgov.sharepoint.com/:i:/r/teams/04708/Shared%20Documents/Research/Usability%20Testing/Screenshots/9-%20Spacing%20issues.png?csf=1&web=1&e=dRtqKI

**Comment by rgreensp** [comment]
Resolved.
