### ISSUE TITLE
14 - BCeID Login Internal Server Error

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/connectivity-intake#223]

**Comment by zoeyli-46** [comment]
Internal server error after clicking Begin on Safari, Chrome, Edge, on Thinkpad, no VPN. The error does not appear after using Incognito mode. 
https://bcgov.sharepoint.com/:i:/t/04708/EWztK9qQiQ9BiYQrEmWqlpgBaUKtdRIRd3zloZKtlC5c-g?e=kmdgm3

**Comment by BryanGK** [comment]
@wenzowski I've been having this issue as well. To fix it I go and remove cookies from the browser then restart the browser. Do you have an idea of why this is happening and how we can fix it?

**Comment by rgreensp** [comment]
@BryanGK I created a BCeID and returned to the test site to log in. I got a 403 error. (On the user testing sheet as number 23. When I closed the browser and opened a new incognito window it worked. I think this is likely part of the same problem?

**Comment by BryanGK** [comment]
This is likely due to a "siteminder" issue unrelated to our project. The appropriate teams have been informed.
