### ISSUE TITLE
26 - Typo on backbone page

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-intake#234]
Add "Max. 3500 characters". Fields are not marked optional, but form lets you proceed with them blank. Can we mark them (if applicable)?

https://bcgov.sharepoint.com/:i:/r/teams/04708/Shared%20Documents/Research/Usability%20Testing/Screenshots/26%20-%20Typos.jpg?csf=1&web=1&e=1nK48u

**Comment by zoeyli-46** [comment]
I feel that because the question is worded in a way that it is conditional, it is intuitive that it is optional. "**If** you selected multiple", "**if** you answered no". I think adding "if applicable" could make it confusing and too verbose
