### ISSUE TITLE
28 - Blank Page when hit "Review"

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-intake#236]
When I am on the Geomark link page and I click review, then I see a blank page. When I click the back button, and then click "review" again, I can see my answers.

Is this error able to be recreated?

**Comment by BryanGK** [comment]
Needs a page at /error, really basic. for now,.

**Comment by BryanGK** [comment]
Likely a network issue not loading the page correctly. Lets keep an eye on it and re-open if necessary.
