### ISSUE TITLE
29 - Cannot Resume

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/connectivity-intake#237]

**Comment by zoeyli-46** [comment]
When logging in with BCeID Basic, and hit "Resume" There is a 500 Error.

Page: login page

https://bcgov.sharepoint.com/:i:/r/teams/04708/Shared%20Documents/Research/Usability%20Testing/Screenshots/29%20-%20Resume%20Error.png?csf=1&web=1&e=VZOQ2r

**Comment by BryanGK** [comment]
This should be solved, but lets keep an eye on it and we can re-open if required.
