### ISSUE TITLE
Review Page's fixes

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#245]
The following are the changes made to the review page after revisions from Ministry & Legal. They are organized by heading.

### Organization Information
- [x] Added field: Organization type

### Proposed Zone Feedback
- [x] Added field: "Which zones are you providing feedback for?"
- [x] Removed: "3500 characters" from Do you have any feedback on the proposed zone boundaries? If you were to apply to a funding program by zone, are there changes to the zone boundaries that would make that process easier?

### Backbone to Support Last Mile
- [x] Changed first question to: Is there existing backbone infrastructure to deliver the last mile projects specified in the previous question?

### Additional Information
- [x] Title changed from Addition Questions to Additional Information
- [x] First question changed to: Are there any pending projects, and/or connectivity plans you would like to inform the Province about? For example, any additional information on planned projects including technology, number of households, communities reached, existing backbone leveraged, and new backbone that you like to include or any consultation on a proposed project taking place.
- [x] Second question changed to: In the information linked in Appendix C of the Request to Participate, some areas were proposed to be best served by satellite. How do these proposed areas align with the expectations of your organization or your community? Please provide feedback on the modelling assumptions.
NOTE: Order of questions on this page changed, 2 & 3 swapped places. Second & third here refers to the updated order.
- [x] Third question changed to: In underserved areas where your Geomark does not indicate a wired or wireless technology viability to serve those households, how could service providers be incentivized to serve those areas? Please note, Geomark files are uploaded on the final page of this form.

### Highway cellular
- [x] First question changed to: If funding was available for capital costs, which sections of highway would be your priority to be completed? Please consider traffic, consumption and other factors.

### Connectivity areas of focus for local governments and First Nations
- [x] Added heading: Areas of Focus for Connectivity for Local and Indigenous Governments
- [x] Added field: What additional feedback do you have for your area? Please include information on areas that are underserved, as well as any other local information considered relevant. This response will be related to the zone(s) specified and could include any particular area of focus for local governments, including challenges with infrastructure or information pertinent to the area.

**Comment by BryanGK** [comment]
Changes implemented - CLOSED
