### ISSUE TITLE
Help email opens in same tab

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#249]
### Bug 
In Chrome (but not Firefox), clicking the help button opened outlook in the same tab, which made me worried I had lost my progress.

It would be better to open it in a new tab or window.

**Comment by elliottSlee** [comment]
Clicking the help button opened outlook in the same tab, which made me worried I had lost my progress. It would be better to open it in a new tab or window.

**Comment by rgreensp** [comment]
Now opens in email window.
