### ISSUE TITLE
Logout Button when logged-out

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#256]
As a respondent,
I don't want to see a logout button, unless I'm logged-in
so that I'm not confused as to my logged-in/logged-out status

DoD:

- [x] logout button changes to login when user is logged-out

**Comment by elliottSlee** [comment]
Swap logout button to the login button on the login page

**Comment by BryanGK** [comment]
@rgreensp The work has been completed on this issue. Can you please review on the test server https://connectivity-rtp-test.apps.silver.devops.gov.bc.ca/ and either let me know it's or you can go in and hit the deploy to prod button in the github action.
