### ISSUE TITLE
Org type as radio button

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#260]
On the "Organization type" page, input should be radio buttons not checkboxes.

**Comment by BryanGK** [comment]
The easiest way to accomplish this would be to use a dropdown menu, where they can select one from a list. Would that be acceptable over the checkboxes where they can select more than one?

**Comment by BryanGK** [comment]
![Screenshot from 2022-03-15 08-13-26](https://user-images.githubusercontent.com/75629890/158409796-e227464b-9a55-487e-80e3-fd92d03efcaf.png)

**Comment by elliottSlee** [comment]
If that's the way it works, then go for it. Usually a radio button's preferable if there are few options and you don't want one to be emphasized (https://blog.prototypr.io/7-rules-of-using-radio-buttons-vs-drop-down-menus-fddf50d312d1), but not a big deal for this form.

**Comment by rgreensp** [comment]
No longer necessary.
