### ISSUE TITLE
Zone information - copy edit

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-intake#268]
Current sentence ends in "for" 

Change to "Zones for which you are providing feedback."

**Comment by elliottSlee** [comment]
I believe this should be deprioritized. Not ending a sentence with a preposition is a myth and [the "rule" has no basis in grammar or readability](https://www.grammarbook.com/blog/definitions/dont-end-a-sentence-with-a-preposition-where-did-this-myth-come-from/).
