### ISSUE TITLE
Make a clicky thing that's online - Metabase

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#282]
- [x] Leverage existing common component helm chart for metabase
- [x] Connect metabase to data

**Comment by BryanGK** [comment]
@rgreensp please let me know if you need any accesses to data about the current state of the deployment re: getting more resources for setting up metabase. Sysdig is already up and collecting information.

**Comment by BryanGK** [comment]
https://ccbc-metabase-dev.apps.silver.devops.gov.bc.ca/
