### ISSUE TITLE
Wireframe of error page

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/connectivity-intake#284]
As a respondent, when I encounter an error I want to know what to do to remedy the error so that I fix things and get back to the form.

For 404, 500, and form error.

**Comment by elliottSlee** [comment]
@BryanGK here's the wireframe for the error page: https://miro.com/app/board/uXjVOY6rC94=/?moveToWidget=3458764521440139533&cot=14
Let me know what you think of it.

**Comment by RajGurtata** [comment]
@elliottSlee Alec and I see the '500 error' and the '404 page not found' in the RTP form

we don't see 500 and 404 screens on the wireframes; and we are wondering if what is in the wireframe is the 'Form error'

Are you able to create wireframes for all 3 errors; with the priority being the one that is presently blank (Form error)

**Comment by elliottSlee** [comment]
@RajGurtata & @wenzowski, what’s meant by gotten error page? A user types an error?

**Comment by elliottSlee** [comment]
I created a mock up on [Miro](https://miro.com/app/board/uXjVOY6rC94=/?moveToWidget=3458764521544834784&cot=14). Do we know what might cause a form error so we can make the error message more informative?
