### ISSUE TITLE
Monitor Error rate using Sysdig

### ISSUE THREAD

**Issue by RajGurtata** [bcgov/connectivity-intake#289]

**Comment by BryanGK** [comment]
@rgreensp @RajGurtata  Are you two able to see the error rate under "Shared Dashboards"?

**Comment by RajGurtata** [comment]
Hi Bryan, I'm in Sysdig but I don't see the error rate dashboard; these are the ones I can see 
![image](https://user-images.githubusercontent.com/96551523/160464580-baa2844c-2a43-41fc-a202-74d6b2d35681.png)

**Comment by BryanGK** [comment]
@RajGurtata At the bottom above `Chat with us` Click your name, and inside there select the `bc5936-tools` namespace. Then go the the `Network` dashboard. Let me know if this works.

**Comment by RajGurtata** [comment]
I got onto ‘bc5936-teams’ and found the 'Network' Dashboard but I have more than a few options. Lemme know if its easier to hop on a call or if you want to advise which from the list I should be looking at

![image](https://user-images.githubusercontent.com/96551523/160489837-560332ac-064b-4f9b-9a84-eb04d86f9b75.png)

**Comment by BryanGK** [comment]
![Screenshot from 2022-03-28 14-28-27](https://user-images.githubusercontent.com/75629890/160490426-a9a8ecd8-ab2d-4625-91ed-c0b0346428f2.png) This is I see. `requests vs. errors` and `errors by app pod` are two of the error metrics.

**Comment by RajGurtata** [comment]
Thanks Bryan I was able to get this displaying correctly; @rgreensp let me know if you need any help getting this to display

![image](https://user-images.githubusercontent.com/96551523/160494165-fedfb7db-10fb-47b3-a392-98ae29645040.png)
