### ISSUE TITLE
Login using BCeID

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#30]

**Comment by rgreensp** [comment]
Access to environments requested.

**Comment by rgreensp** [comment]
Tomorrow we'll need to paste the JSON here from this process. https://bcgov.github.io/sso-requests/my-requests?id=2014&mode=edit

**Comment by BryanGK** [comment]
> Tomorrow we'll need to paste the JSON here from this process. https://bcgov.github.io/sso-requests/my-requests?id=2014&mode=edit

@rgreensp Have you gotten the JSON to paste here?

**Comment by rgreensp** [comment]
Dev: {
  "confidential-port": 0,
  "auth-server-url": "https://dev.oidc.gov.bc.ca/auth",
  "realm": "onestopauth-basic",
  "ssl-required": "external",
  "public-client": true,
  "resource": "connectivity-intake-2014"
}

**Comment by rgreensp** [comment]
Test: 
{
  "confidential-port": 0,
  "auth-server-url": "https://test.oidc.gov.bc.ca/auth",
  "realm": "onestopauth-basic",
  "ssl-required": "external",
  "public-client": true,
  "resource": "connectivity-intake-2014"
}

**Comment by rgreensp** [comment]
- Rachel needs to email Tim about instruction language and "are we good?" based on last email asking for information.

- Testing is part of SSO express package. https://github.com/bcgov/cas-template-app/tree/develop/packages/sso-express

- Should test if BCeID Business works in the BCeID basic box.
