### ISSUE TITLE
User Story Template

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#304]
Create an issue template in the repo "CONN-CCBC-portal" with the text below:

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

**As a** [type of user or profile] (who performs the action?)
**I want** [action] (what they are doing?)
**so that** [reason behind goal] (why this is important? What problem is this solving?)

### Description: 

_(Brief description of the work involved, including any user research context or key decisions.)_

### Acceptance Criteria:

- [ ] Task
- [ ] Task
- [ ] Task

----

### Is this story Ready?

- [ ]  **Has the story the INVEST criteria** 
- “I” ndependent (of all others as practicable) 
- “N” egotiable (not a specific contract for features) 
- “V” aluable (or vertical) 
- “E” stimable (to a good approximation) 
- “S” mall (so as to fit within an iteration) 
- “T” estable (in principle, even if there isn’t a test for it yet) 
- [ ]  **It has Acceptance Criteria.**
- [ ]  **It has a Prototype (low or high fidelity) (optional).**
- [ ]  **It has the Stakeholders’ agreement.**
- [ ]  **The Acceptance Criteria was evaluated by the Dev Team (Feasible or not).**
- [ ]  **Another person can execute it without further questions (clarity).**
- [ ] A user story is clear if all Scrum team members have a shared understanding of what it means. Collaboratively writing user stories, and adding acceptance criteria to the high-priority ones facilitates clarity  
- [ ] An item is testable if there is an effective way to determine if the functionality works as expected. Acceptance criteria ensure that each story can be tested  
- [ ] A user story is feasible if it can be completed in one sprint, according to the Definition of Done. If this is not achievable, it needs to be broken down further

**Comment by eazeredo** [comment]
@marcellmueller , could you add this as an issue template?

**Comment by marcellmueller** [comment]
@eazeredo I added the template in the CCBC repository and added you as a reviewer:

https://github.com/bcgov/CONN-CCBC-portal/pull/118
