### ISSUE TITLE
Content for begin/resume application page

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#34]
Should support UX of application process:
- who should be filling out this form
- how long will it take to apply to the program
- what information will be needed to complete
- what happens if they lose username/password
- that they can start/come back to form
- dates/deadlines for completion of application
- timeline on gov response to applicants
- how information will be used
- any legal stuff

**Comment by rgreensp** [comment]
- Rachel to send FOIPPA language to Elliott/Bryan for form internal landing page
- Instructions have been drafted. Need to review against this card to ensure completion.
- BCeID piece needs to be send to Tim McGuire, Geomark piece needs to be sent to Brian.

**Comment by rgreensp** [comment]
Dupe of #31
