### ISSUE TITLE
Persist applicant profile in database

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#35]
- copy info from page one of the pre-screen application form: https://www.northerndevelopment.bc.ca/funding-programs/partner-programs/connecting-british-columbia/economic-recovery-intake/

- How do you qualify for this program. copy eligibility from FAQ (what are the eligibility requirements for the program)

- multiple questions to ensure applicants qualify

- textbox at the end for notes? (Raj)

**Comment by rgreensp** [comment]
Closing. Duplicate of #81.
