### ISSUE TITLE
RTP - Questions 

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#38]
Based on data we need to collect, reflected in this Word doc: https://bcgov.sharepoint.com/:w:/r/teams/04708/Shared%20Documents/Data%20and%20mapping/2022-01-10RTP%20Zone%20Form%20Questions.docx?d=wbde7fc679b8f45dfbb5d994e4fbef099&csf=1&web=1&e=ys4nyZ

- [x] Mock up questions for Howard review and approval
- [x] Mock up UX wireframe for how questions will look in form. 
- [x] Examine changes from lawyers.
- [x] Create paper/pdf version of instructions/information sheet to accompany form
- [x] Determine how many geomarks are required and where they will be submitted.
- [x] Approval of questions and appearance.

**Comment by wenzowski** [comment]
This will be faster to implement via dependent fields on the same page rather than dependent form pages based on which zone checkboxes are checked.

**Comment by elliottSlee** [comment]
Most up-to-date version of questions is https://bcgov.sharepoint.com/:w:/r/teams/04708/Shared%20Documents/Content/RTP%20Zone%20Form%20Questionnaire%20v4.docx?d=w34c1becc912346399c7e15f7813ff197&csf=1&web=1

**Comment by elliottSlee** [comment]
Skipped to creating hybrid of high-fidelity wireframe and user journey because of time constraint. It can be found at https://miro.com/app/board/uXjVOY6rC94=/?moveToWidget=3458764517299961720&cot=14

**Comment by elliottSlee** [comment]
As the connectivity team, we want to have clear, succinct responses without unnecessary or repetitive information so that we can make sense of responses.

**Comment by elliottSlee** [comment]
As a respondent, I want to submit information once so that the form does not take too long to complete.
