### ISSUE TITLE
Company profile draft flow

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#44]
Create a form flow for creating a company profile within the application

https://miro.com/app/board/uXjVOY6rC94=/

**Comment by rgreensp** [comment]
Implement form for company information collection. 
- Contact information
- Type of organization
- What type of projects, how will you qualify

**Comment by rgreensp** [comment]
@BryanGK, we need to remove the "how will you qualify" questions from the scope of this card, as we are no longer using the RTP to gauge how applicants qualify. Leave the "who are you" and "contact info"
