### ISSUE TITLE
User flow for applicant 

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#45]
Create a user flow for submitting an RTP thru the app

**Comment by rgreensp** [comment]
Definition of done:
- Miro of screen snapshots for applicant user journey
- Mural of user journey for Connectivity Division

**Comment by BryanGK** [comment]
As a program admin
I want to see a visual of the application workflow
so that I can confirm the process steps

DoD:
- [ ] Miro of screen snapshots for applicant user journey
- [ ] Mural of user journey for Connectivity Division

**Comment by rgreensp** [comment]
Can revise based on learnings this week. Will finalize based on question fields.
