### ISSUE TITLE
Create landing page for applicant

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#47]
As a program applicant
I want to see a landing page once logged in that displays in progress applications, submitted applications, and a new application button
so that I can have my options and information consolidated in one page.

AC:

- [ ] new page that display in-progress applications, submitted applications, and a new application button
- [ ] screenshot and share to Miro board for customer review

**Comment by rgreensp** [comment]
No longer relevant for RTP. Will create new cards for Intake.
