### ISSUE TITLE
Create confirmation page

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#49]
As a program applicant
I want an application received confirmation page
so that I can be sure my application has been received

*this page should be made as a mock-up with no real functionality

AC:
- [x] new page with form data displayed before setting "complete status"
- [x] Button to Go back to the form 
- [x] Button to "submit" form data (changing status to "complete")
- [x] Form data displayed in the correct areas for user review

**Comment by rgreensp** [comment]
Ref #195
