### ISSUE TITLE
Boilerplate pipeline code

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#6]
There are boilerplate examples of successful pipelines that can be copied and re-used.

- [x] Collect list of examples
- [x] Evaluate examples for conformance with best practices
- [x] Determine which example we wish to use
- [x] Copy code and push to repo
- [x] Test deployment

**Comment by wenzowski** [comment]
Maybe we could collect the links to the sources of pipeline inspiration here? eg. https://github.com/bcgov/pipeline-templates

Let's make sure we choose a modern CI technology (eg. Github Actions) as we heard from Platform Services that Jenkins is currently using 52% of the Silver cluster and they're keen to avoid adding to that load.

**Comment by wenzowski** [comment]
Open question: what makes a good example?
