### ISSUE TITLE
Checkboxes in form

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#68]
Check boxes are not implemented in the schema form. @wenzowski We will put in issue in Button team channel to get this moving forward.

ref #44

**Comment by BryanGK** [comment]
Checkboxes sorted - CLOSED

**Comment by wenzowski** [comment]
@BryanGK let's make sure that moving forward we get product owner acceptance of features like this: the checkboxes are there–but do they conform to our design system, and is this specific implementation accepted? We'll open a new ticket for checkbox improvements as necessary; no need to reopen this card.

**Comment by BryanGK** [comment]
@wenzowski Yep sounds good. Will get approval from PO moving forward.
