### ISSUE TITLE
Boilerplate application code

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#7]
There are boilerplate examples of successful nextjs applications that can be copied and re-used.

- [x] Determine which example we wish to use
- [x] Copy code and push to repo
- [x] Test application

**Comment by wenzowski** [comment]
I'd really like to explore opportunities to use the [service-development-toolkit](https://github.com/button-inc/service-development-toolkit) to accelerate delivery of this project. Perhaps we can split further–[a hello world page using the common components](https://button-inc.github.io/service-development-toolkit/@button-inc/bcgov-theme/index.html?path=/docs/getting-started-toolkit-in-action--default), and a form using [react-jsonschema-form](https://service-development-toolkit.herokuapp.com/form-builder).

**Comment by wenzowski** [comment]
Maybe we should be looking at [nextjs-with-styled-components](https://github.com/button-inc/service-development-toolkit/tree/develop/examples/nextjs/nextjs-with-styled-components)

**Comment by wenzowski** [comment]
This story is really only about boilerplate for a hello world; we'll have next stories for adding a static form that corresponds to the schema, and for getting that schema into the database in a versioned manner, and for getting form submissions persisted against the version of the form users are filling out, and for authentication so only authenticated users can fill out the form

**Comment by wenzowski** [comment]
I would lean towards scheduling this before #6
