### ISSUE TITLE
Form field fixes

### ISSUE THREAD

**Issue by BryanGK** [bcgov/connectivity-intake#77]
The form needs some fixing

DoD:
- [x] textarea fields don't show correctly
- [x] duplicate labels in pre-screen page

**Comment by zoeyli-46** [comment]
Mar 9 Changes:
Please directly copy paste wording from MIRO wireframe 

**All Pages**
Help link in nav bar leads to emailing connectingcommunitiesbc@gov.bc.ca
Page Headers renamed from Request to Participate to Connecting Communities BC 

**Form landing page**
All text on the card has changed 

**Dashboard**
Wording in "About this form" section has changed 

**Organization Profile Page 1**
New page that asks for Organization Type

**Zone information**
Page title changed to "Zone Information"
Wording changes to all questions and page description 

**Technology viability**
Page title changed to Areas of Focus for Technology Viability
Wording changes to all questions and page description

**Backbone**
Page title changed to Backbone Infrastructure to Support Last Mile
Page description, Question 1, and Question 3 have minor wording adjustments

**Additional Information**
Page title changed to Additional Information 

**Highway Cellular**
Page description and Question 1 changed 

**LG and IG**
Entirely new page added

**Upload Geomarks**
Page description and each form field title has wording changes
