### ISSUE TITLE
RTP - Cellular Questions

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-intake#89]
Based on data we need to collect, reflected in this Word doc: https://bcgov.sharepoint.com/:w:/r/teams/04708/Shared%20Documents/Data%20and%20mapping/2022-01-10RTP%20Zone%20Form%20Questions.docx?d=wbde7fc679b8f45dfbb5d994e4fbef099&csf=1&web=1&e=ys4nyZ

 Mock up questions for Howard review and approval
 Mock up UX wireframe for how questions will look in form.
 Approval of questions and appearance.

**Comment by elliottSlee** [comment]
Cellular & Zone Questions have been combined. This issue is therefore combined with #38.
