### ISSUE TITLE
Test/prod environments

### ISSUE THREAD

**Issue by rgreensp** [bcgov/connectivity-intake#91]

**Comment by rgreensp** [comment]
Test and prod environments need Github environments. Also need to check that Helm charts are stable. 

DoD:
- All dev test and prod environments are deployed using Github environments via Helm.

**Comment by BryanGK** [comment]
- [ ] set up github environment for dev
- [ ] set up github environment for test
- [ ] set up github environment for prod
- [ ] input necessary secrets and values into respective environments
- [ ] determine branches and timing of when deployments should happen
